### ISSUE TITLE
scrapy ValueError: Missing scheme in request url:

### ISSUE THREAD

**Issue by kn9** [Lazar-T/get_emails#1]
Hi I'm new with python and scrapy, I'm getting the error below please how can I sort this out. 
thank you.

root@4i41:/home/addm/emails# scrapy crawl emails
2017-12-28 00:23:36 [scrapy.utils.log] INFO: Scrapy 1.4.0 started (bot: get_emails)
2017-12-28 00:23:36 [scrapy.utils.log] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'get_emails.spiders', 'SPIDER_MODULES': ['get_emails.spiders'], 'BOT_NAME': 'get_emails'}
2017-12-28 00:23:36 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2017-12-28 00:23:36 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-12-28 00:23:36 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-12-28 00:23:36 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2017-12-28 00:23:36 [scrapy.core.engine] INFO: Spider opened
2017-12-28 00:23:36 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-12-28 00:23:36 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2017-12-28 00:23:36 [scrapy.core.engine] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 127, in _next_request
    request = next(slot.start_requests)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiders/__init__.py", line 83, in start_requests
    yield Request(url, dont_filter=True)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/http/request/__init__.py", line 25, in __init__
    self._set_url(url)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/http/request/__init__.py", line 58, in _set_url
    raise ValueError('Missing scheme in request url: %s' % self._url)
ValueError: Missing scheme in request url: blocklevel.com
2017-12-28 00:23:36 [scrapy.core.engine] INFO: Closing spider (finished)
2017-12-28 00:23:36 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'finished',
 'finish_time': datetime.datetime(2017, 12, 28, 0, 23, 36, 508227),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'memusage/max': 55283712,
 'memusage/startup': 55283712,
 'start_time': datetime.datetime(2017, 12, 28, 0, 23, 36, 503571)}
2017-12-28 00:23:36 [scrapy.core.engine] INFO: Spider closed (finished)
root@4i41:/home/addm/emails#

**Comment by Lazar-T** [comment]
Hi, in csv file instead of blocklevel.com you can enter http://blocklevel.com

**Comment by kn9** [comment]
Ok, thank you will try that and get back to you.
